#!/usr/bin/env python3
"""Generate the geocontract master JSON Schema from the pinned ODCS v3.1.0 schema.

The ODCS v3.1.0 canonical schema declares ``additionalProperties: false`` at
the top level, which makes it impossible to extend via ``allOf`` (any new
property is rejected by the base subschema). The geocontract master schema is
a **derivative** that:

1. Inherits every ODCS ``$defs`` and top-level property unchanged.
2. Replaces the top-level ``additionalProperties: false`` with
   ``unevaluatedProperties: false`` (annotation-based, so it composes).
3. Adds a single new top-level property, ``embeddedSchemas``, that lets a
   geocontract contract carry one or more arbitrary nested JSON Schemas —
   e.g. the DCAT-US 3.0.0 Catalog schema, the NEPA exclusions source
   schema, or any agency-published domain schema. The federated harvester
   uses these embedded schemas to validate harvested records.

This script is the single source of truth for
``external/geocontract-master.schema.json``. Re-run it after bumping the
pinned ODCS schema:

    uv run python scripts/build_master_schema.py

The generator is deterministic: the same input always produces the same
output (keys are written in sorted order).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
ODCS_SCHEMA = ROOT / "external" / "odcs-json-schema-v3.1.0.json"
MASTER_SCHEMA = ROOT / "external" / "geocontract-master.schema.json"

MASTER_ID = "https://geocontract.dev/schemas/geocontract-master.schema.json"
# The JSON Schema draft meta-schema URI that an embedded schema may be
# validated against. We keep this as a structural reference; the validator
# does not fetch it over the network.
EMBEDDED_META_REF = "https://json-schema.org/draft/2019-09/schema"


def _deep_copy(obj: Any) -> Any:
    return json.loads(json.dumps(obj))


def build_master(odcs: dict) -> dict:
    """Produce the geocontract master schema from the ODCS v3.1.0 schema."""
    master = _deep_copy(odcs)

    # Re-identify as the geocontract master; keep $schema (draft) as-is so
    # the same validator draft applies.
    master["$id"] = MASTER_ID
    master["title"] = "geocontract Master Data Contract Schema (ODCS v3.1.0 + embeddedSchemas)"
    master["description"] = (
        "Derivative of the canonical ODCS v3.1.0 JSON Schema that adds a "
        "top-level `embeddedSchemas` property. Each value in embeddedSchemas "
        "is an arbitrary nested JSON Schema (e.g. the DCAT-US 3.0.0 Catalog "
        "schema, the NEPA exclusions source schema, or any agency-published "
        "domain schema). The federated harvester uses the embedded schemas "
        "to validate harvested records. Generated by "
        "scripts/build_master_schema.py — do not edit by hand."
    )

    # The core change: swap additionalProperties → unevaluatedProperties so
    # that the new `embeddedSchemas` property composes cleanly. ODCS's own
    # nested objects keep their (stricter) additionalProperties: false.
    master.pop("additionalProperties", None)
    master["unevaluatedProperties"] = False

    props = master.setdefault("properties", {})
    props["embeddedSchemas"] = {
        "type": "object",
        "title": "Embedded JSON Schemas",
        "description": (
            "A map of named, arbitrary nested JSON Schemas that extend this "
            "contract with domain-specific payload validation. Each key is a "
            "stable schema name (e.g. `dcatUsCatalog`, `nepaExclusions`); "
            "each value is a JSON Schema document (inline or with a `$ref`). "
            "The federated harvester validates harvested records against the "
            "matching embedded schema."
        ),
        "additionalProperties": {
            # Each value must be a JSON Schema object. We require the
            # minimal structural markers of a JSON Schema so that a typo
            # (e.g. pasting a data instance by mistake) is caught early.
            "type": "object",
            "anyOf": [
                {"required": ["type"]},
                {"required": ["$ref"]},
                {"required": ["properties"]},
                {"required": ["allOf"]},
                {"required": ["oneOf"]},
                {"required": ["anyOf"]},
                {"required": ["enum"]},
                {"required": ["const"]},
            ],
            # Point at the draft meta-schema for provenance; the validator
            # treats this as documentation and does not fetch it.
            "$schema": EMBEDDED_META_REF,
        },
        "propertyNames": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9_-]*$",
            "description": "Schema names are stable identifiers (camelCase or kebab-case).",
        },
    }

    return master


def main() -> int:
    odcs = json.loads(ODCS_SCHEMA.read_text())
    master = build_master(odcs)
    MASTER_SCHEMA.write_text(json.dumps(master, indent=2, sort_keys=True) + "\n")
    print(f"OK   wrote {MASTER_SCHEMA.relative_to(ROOT)} ({MASTER_SCHEMA.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
