#!/usr/bin/env bash
# generate_graphql.sh — generate GraphQL SDL from x-graphql-annotated templates.
#
# The SDL files under models/*.canonical.graphql are GENERATED artifacts:
# they are produced by running the vendored json-schema-x-graphql converter
# (`jxql`) over the matching template under templates/. Do not hand-edit
# them — re-run this script (`mise run generate-graphql`) after changing a
# template.
#
# The Catalog type is declared under $defs/Catalog with
# `x-graphql-type-name: DcatCatalog` so jxql emits it with the canonical
# name; the root is a thin allOf wrapper that generates no GraphQL type.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
JXQL="${JXQL:-${ROOT}/.tools/bin/jxql}"

if [[ ! -x "${JXQL}" ]]; then
  echo "ERROR: jxql not found at ${JXQL}. Run 'mise run vendor-jxql' first." >&2
  exit 1
fi

# (template, output)
generate() {
  local template="$1"
  local output="$2"

  echo "▸ generating ${output} from ${template}"
  "${JXQL}" \
    --input "${ROOT}/${template}" \
    --output "${ROOT}/${output}" \
    --descriptions --preserve-order \
    --federation-version 2 \
    --naming-convention GRAPHQL_IDIOMATIC \
    --id-strategy NONE \
    --output-format SDL_WITH_FEDERATION_METADATA

  # Prepend a generated-artifact header so the file is never mistaken
  # for hand-curated source. This is a build step, not curation: the
  # body below the header is the unmodified jxql output.
  local tmp
  tmp="$(mktemp)"
  {
    echo "# GENERATED by scripts/generate_graphql.sh — do not edit by hand."
    echo "# Source: ${template}"
    echo "# Regenerate: mise run generate-graphql"
    echo "#"
    cat "${ROOT}/${output}"
  } > "${tmp}"
  mv "${tmp}" "${ROOT}/${output}"
  echo "✓ ${output}"
}

generate \
  "templates/dcat-us-catalog.template.schema.json" \
  "models/dcat-us-catalog.canonical.graphql"

generate \
  "templates/nepa-exclusions.template.schema.json" \
  "models/nepa-exclusions.canonical.graphql"

generate \
  "templates/pic-standards.template.schema.json" \
  "models/pic-standards.canonical.graphql"
